default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: expensetracker
  password: "nurin1207"
  host: localhost

development:
  <<: *default
  database: expensetracker_development

test:
  <<: *default
  database: expensetracker_test

production:
  <<: *default
  database: expense_tracker

cable:
  adapter: redis
  url:redis//localhost:6379/1
